# Travis CI configuration file for running tests
language: python
python:
  - "2.7"
install:
  - "pip install --allow-all-external -r requirements.txt"
script:
  - nosetests tests.gen_cert_test:test_cert_gen
